// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yabldejwifckbuutyppe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhYmxkZWp3aWZja2J1dXR5cHBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTIxMjUsImV4cCI6MjA3MTM2ODEyNX0.Lm2CCVew6qD4TGBVDHlC7G9y1cClOJ1NAwOeEZVZhUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});